# Generated by Django 3.2.15 on 2023-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
    ]
