# Generated by Django 3.2.15 on 2023-03-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_cryptocurrency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='percent_change',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30),
        ),
    ]
